version: 1.0.{build}
configuration: Release
platform: Any CPU
build:
  project: SockNet.sln
  verbosity: minimal
nuget:
  account_feed: true
  project_feed: true
after_build:
- ps: '7z a SockNet.zip SockNet.Common\bin\Release\SockNet.Common.dll'
- ps: '7z a SockNet.zip SockNet.Client\bin\Release\SockNet.Client.dll'
- ps: '7z a SockNet.zip SockNet.Server\bin\Release\SockNet.Server.dll'
- ps: '7z a SockNet.zip SockNet.Protocols\bin\Release\SockNet.Protocols.dll'
artifacts:
- path: 'SockNet.zip'